### ISSUE TITLE
How to change data for timezones?

### ISSUE THREAD

**Issue by AntonTaran** [kevalbhatt/timezone-picker#19]
I want to change timezones array. This is a static array in timezone-picker-min.js and I have no idea how to call a plugin with my own data array. Thanks.

**Comment by kevalbhatt** [comment]
https://github.com/kevalbhatt/timezone-picker/blob/master/src/TimezonePicker.js#L131 as you can see i am assigning imported  timezone obj val to the this.timezone obj.

You can override generateMap(options) because right now we dont have option to pass json in config. 

I will create new issue to allow user to pass json in config.

**Comment by AntonTaran** [comment]
Thanks a lot for your answer. Great plugin. I look forward to updates. Have
a nice day.

Best regards,
Anton


вс, 27 янв. 2019 г. в 11:13, Keval Bhatt <notifications@github.com>:
