### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getValue' of undefined

### ISSUE THREAD

**Issue by dotmaik1** [kevalbhatt/timezone-picker#4]
I already rendered the map and I get to select a timezone but when I try to get the value when I click a button I get the error 

> Uncaught TypeError: Cannot read property 'getValue' of undefined

Here is my code:

`function saveTz() {
        var tz = $('.dropdown-toggle').data('timezonePicker').getValue();
            console.log(tz[0].timezone);
            alert(tz[0].timezone);
    }`

How can I get the actual value to save it in a database when I click a button?

Thanks and Regards

**Comment by kevalbhatt** [comment]
@dotmaik1 your selector is wrong that is why **$('.dropdown-toggle').data('timezonePicker')** is undefined and because of this, you are getting this error.

> Uncaught TypeError: Cannot read property 'getValue' of undefined.

**Solution**.

you will get timezonePicker data object when you use the same selector which you used while initializing plugin.

**Example**:

In my [example.html](https://github.com/kevalbhatt/timezone-picker/blob/master/example.html#L14) I have initialized plugin using **$(#map)** selector. so when I want to get the value I will get it like this.

```JS
$(#map).data('timezonePicker').getValue();
```
**Reference**:

[How to use Jquery.data() ](https://api.jquery.com/data/)

**Comment by kevalbhatt** [comment]
@dotmaik1 is your problem resolved?
